
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-terraform-deployer-e4ca1d-token
  namespace: e4ca1d-tools
  annotations:
    kubernetes.io/service-account.name: sysdig-terraform-deployer-e4ca1d
type: kubernetes.io/service-account-token
