name: Deploy Sysdig Teams via Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "sysdig-teams/**"
      - ".github/workflows/sysdig-teams.yml"

jobs:
  deploy-sysdig-teams:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - plate: c6af30
          - plate: eb75ad
          - plate: e4ca1d
          - plate: b29129
    steps:
      - uses: hmarr/debug-action@v3
      - uses: actions/checkout@v4

      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          kam: "latest"
          oc: "4"
      - name: Login Openshift Gold
        uses: ./.github/actions/oc-login
        with:
          namespace: ${{ matrix.plate }}-tools
          oc-server-gold: ${{ secrets.OPENSHIFT_SERVER_GOLD }}
          oc-token-gold: ${{ secrets.OPENSHIFT_TOKEN_GOLD }}

      - name: Deploy Sysdig Team via Helm chart
        run: ./deploy-${{ matrix.plate }}.sh
        working-directory: ./sysdig-teams
