name: Deploy Sysdig Teams via Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "sysdig-teams/**"
      - ".github/workflows/sysdig-teams.yml"

jobs:
  deploy-sysdig-teams:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - plate: c6af30
          - plate: eb75ad
          - plate: e4ca1d
          - plate: b29129
    steps:
      - uses: hmarr/debug-action@v3
      - uses: actions/checkout@v4

      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          kam: "latest"
          oc: "4"

      - name: Login Openshift Gold
        uses: ./.github/actions/oc-login
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_GOLD }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_GOLD }}
          namespace: ${{ matrix.plate }}-tools
          insecure_skip_tls_verify: true

      - name: Deploy Sysdig Team via oc
        run: oc -n ${{ matrix.plate }}-tools process -f sysdig-team.yaml -p PROJECT=${{ matrix.plate }} | oc -n ${{ matrix.plate }}-tools apply -f -
        working-directory: ./sysdig-teams
